
export const ADD_PRODUCT = 'ADD_PRODUCT'

export const ADD_ORDER = 'ADD_ORDER'
export const ATTACH_PRODUCT_TO_ORDER = 'ATTACH_PRODUCT_TO_ORDER'

export const ADD_PACKAGE = 'ADD_PACKAGE'
export const ATTACH_PRODUCT_TO_PACKAGE = 'ATTACH_PRODUCT_TO_PACKAGE'
